apiVersion: apps/v1
kind: Deployment
metadata: {name: {{ include "devops-api.fullname" . }}}
spec:
 replicas: {{ .Values.replicaCount }}
 strategy: {type: RollingUpdate, rollingUpdate: {maxUnavailable: 0, maxSurge: 1}}
 selector:
  matchLabels:
   {{- include "devops-api.selector" . | nindent 3 }}
 template:
  metadata:
   labels:
    {{- include "devops-api.selector" . | nindent 4 }}
  spec:
   automountServiceAccountToken: false
   securityContext: {runAsNonRoot: true, runAsUser: 1000, runAsGroup: 1000, fsGroup: 1000, seccompProfile: {type: RuntimeDefault}}
   containers:
    - name: api
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      ports: [{name: http, containerPort: 8080}]
      env:
       {{- range $k,$v := .Values.env }}
       - {name: {{ $k }}, value: {{ $v | quote }}}
       {{- end }}
      securityContext: {allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, capabilities: {drop: [ALL]}}
      resources:
       {{- toYaml .Values.resources | nindent 7 }}
      readinessProbe: {httpGet: {path: /readyz, port: http}, initialDelaySeconds: 5, periodSeconds: 10}
      livenessProbe: {httpGet: {path: /healthz, port: http}, initialDelaySeconds: 10, periodSeconds: 15}
      startupProbe: {httpGet: {path: /healthz, port: http}, periodSeconds: 5, failureThreshold: 12}
      volumeMounts: [{name: tmp, mountPath: /tmp}]
   volumes: [{name: tmp, emptyDir: {sizeLimit: 64Mi}}]
