{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: {name: {{ include "devops-api.fullname" . }}}
spec:
 minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
 selector:
  matchLabels:
   {{- include "devops-api.selector" . | nindent 3 }}
{{- end }}
