data "aws_iam_policy_document" "ecs_tasks_assume" { statement { effect="Allow"; principals { type="Service"; identifiers=["ecs-tasks.amazonaws.com"] }; actions=["sts:AssumeRole"] } }
resource "aws_iam_role" "execution" { name="${var.name}-execution-role"; assume_role_policy=data.aws_iam_policy_document.ecs_tasks_assume.json; tags=var.tags }
resource "aws_iam_role_policy_attachment" "execution" { role=aws_iam_role.execution.name; policy_arn="arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy" }
resource "aws_iam_role" "task" { name="${var.name}-task-role"; assume_role_policy=data.aws_iam_policy_document.ecs_tasks_assume.json; tags=var.tags }
resource "aws_cloudwatch_log_group" "this" { name="/ecs/${var.name}"; retention_in_days=var.log_retention_days; tags=var.tags }
resource "aws_ecs_cluster" "this" { name="${var.name}-cluster"; setting { name="containerInsights"; value="enabled" }; tags=var.tags }
resource "aws_ecs_task_definition" "this" { family=var.name; network_mode="awsvpc"; requires_compatibilities=["FARGATE"]; cpu=tostring(var.cpu); memory=tostring(var.memory); execution_role_arn=aws_iam_role.execution.arn; task_role_arn=aws_iam_role.task.arn; runtime_platform { operating_system_family="LINUX"; cpu_architecture="X86_64" }; container_definitions=jsonencode([{name="app",image="${var.repository_url}:${var.image_tag}",essential=true,portMappings=[{containerPort=var.container_port,hostPort=var.container_port,protocol="tcp"}],environment=[{name="APP_ENV",value=var.environment},{name="PORT",value=tostring(var.container_port)}],healthCheck={command=["CMD-SHELL","python -c "import urllib.request; urllib.request.urlopen('http://127.0.0.1:${var.container_port}/health', timeout=3)" || exit 1"],interval=30,timeout=5,retries=3,startPeriod=15},logConfiguration={logDriver="awslogs",options={"awslogs-group"=aws_cloudwatch_log_group.this.name,"awslogs-region"=var.aws_region,"awslogs-stream-prefix"="app"}}}]); tags=var.tags }
resource "aws_ecs_service" "this" { name="${var.name}-service"; cluster=aws_ecs_cluster.this.id; task_definition=aws_ecs_task_definition.this.arn; desired_count=var.desired_count; launch_type="FARGATE"; platform_version="LATEST"; health_check_grace_period_seconds=60; enable_execute_command=true; deployment_minimum_healthy_percent=100; deployment_maximum_percent=200; deployment_circuit_breaker { enable=true; rollback=true }; network_configuration { subnets=var.private_subnet_ids; security_groups=[var.security_group_id]; assign_public_ip=false }; load_balancer { target_group_arn=var.target_group_arn; container_name="app"; container_port=var.container_port }; lifecycle { ignore_changes=[desired_count] }; tags=var.tags }
resource "aws_appautoscaling_target" "ecs" { max_capacity=var.max_capacity; min_capacity=var.min_capacity; resource_id="service/${aws_ecs_cluster.this.name}/${aws_ecs_service.this.name}"; scalable_dimension="ecs:service:DesiredCount"; service_namespace="ecs" }
resource "aws_appautoscaling_policy" "cpu" { name="${var.name}-cpu-scaling"; policy_type="TargetTrackingScaling"; resource_id=aws_appautoscaling_target.ecs.resource_id; scalable_dimension=aws_appautoscaling_target.ecs.scalable_dimension; service_namespace=aws_appautoscaling_target.ecs.service_namespace; target_tracking_scaling_policy_configuration { target_value=60; scale_in_cooldown=120; scale_out_cooldown=60; predefined_metric_specification { predefined_metric_type="ECSServiceAverageCPUUtilization" } } }
resource "aws_appautoscaling_policy" "memory" { name="${var.name}-memory-scaling"; policy_type="TargetTrackingScaling"; resource_id=aws_appautoscaling_target.ecs.resource_id; scalable_dimension=aws_appautoscaling_target.ecs.scalable_dimension; service_namespace=aws_appautoscaling_target.ecs.service_namespace; target_tracking_scaling_policy_configuration { target_value=70; scale_in_cooldown=120; scale_out_cooldown=60; predefined_metric_specification { predefined_metric_type="ECSServiceAverageMemoryUtilization" } } }
